name: tembo_client
description: A new Flutter package project.
version: 0.0.1
repository: https://github.com/okellogerald/tembo_client

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  smile_identity_plugin: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: circular
      fonts:
        - asset: assets/fonts/CircularStd-Book.ttf
          weight: 400
        - asset: assets/fonts/CircularStd-Medium.ttf
          weight: 500
        - asset: assets/fonts/CircularStd-Bold.ttf
          weight: 600
        - asset: assets/fonts/CircularStd-Black.ttf
          weight: 700