name: tembo_client_sdk
description: Tembo Client SDK.
version: 0.0.1
repository: https://github.com/okellogerald/tembo_client_sdk

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  smile_identity_plugin:
    path: "../smile_identity_plugin/"
  #smile_identity_plugin: ^0.0.1+1
  # smile_identity_plugin:
  #   git:
  #     ref: dev
  #     url: https://github.com/okellogerald/smile_identity_plugin.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
